// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmmXjY8o_HRWzmGguWm9rZ5X_cwMEOPmU',
    appId: '1:456070560664:web:f75c9c6c24c72b145489ed',
    messagingSenderId: '456070560664',
    projectId: 'vital-ef6f0',
    authDomain: 'vital-ef6f0.firebaseapp.com',
    storageBucket: 'vital-ef6f0.firebasestorage.app',
    measurementId: 'G-G3XK05CVEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaXo5N01sPGd_UOpmrVx9XdMDs8O4MVI0',
    appId: '1:456070560664:android:6dc9f3fa40e0e6665489ed',
    messagingSenderId: '456070560664',
    projectId: 'vital-ef6f0',
    storageBucket: 'vital-ef6f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaxzcULN6F124q_qWgHb7PdRlAd2phO8I',
    appId: '1:456070560664:ios:263c08d8f34cf4fc5489ed',
    messagingSenderId: '456070560664',
    projectId: 'vital-ef6f0',
    storageBucket: 'vital-ef6f0.firebasestorage.app',
    iosBundleId: 'com.example.vital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaxzcULN6F124q_qWgHb7PdRlAd2phO8I',
    appId: '1:456070560664:ios:263c08d8f34cf4fc5489ed',
    messagingSenderId: '456070560664',
    projectId: 'vital-ef6f0',
    storageBucket: 'vital-ef6f0.firebasestorage.app',
    iosBundleId: 'com.example.vital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmmXjY8o_HRWzmGguWm9rZ5X_cwMEOPmU',
    appId: '1:456070560664:web:d72cbc7c5cc68cca5489ed',
    messagingSenderId: '456070560664',
    projectId: 'vital-ef6f0',
    authDomain: 'vital-ef6f0.firebaseapp.com',
    storageBucket: 'vital-ef6f0.firebasestorage.app',
    measurementId: 'G-5TPQE1F6S6',
  );
}
